# 代碼功能說明: 語義分類場景庫
# 創建日期: 2026-01-30
# 創建人: Daniel Chung
# 最後修改日期: 2026-02-19

"""語義分類場景庫 - 用於快速判斷查詢類型和處置方式

⚠️  DEPRECATED - 已棄用  ⚠️
此模組不再用於 JP 查詢，請使用 schema_driven_query 模組
"""

SEMANTIC_SCENARIOS = [
    {
        "id": "T2S-001",
        "natural_language": "查詢料號為 10-0001 的庫存記錄。",
        "query_type": "簡單查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM mart_inventory_wide WHERE img01 = '...'",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-002",
        "natural_language": "查詢料號 10-0001 且倉庫為 W01 的庫存。",
        "query_type": "簡單查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... AND ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-003",
        "natural_language": "查詢料號為 10-0001 或 10-0002 的庫存。",
        "query_type": "簡單查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... OR ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-004",
        "natural_language": "查詢料號在 10-0001、10-0002、10-0003 中的庫存。",
        "query_type": "簡單查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... IN (...)",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-005",
        "natural_language": "計算料號 10-0001 的總庫存量。",
        "query_type": "聚合查詢",
        "handling": "執行",
        "sql_structure": "SELECT SUM(img10) ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-006",
        "natural_language": "查詢料號 10-0001 在各倉庫的平均庫存量。",
        "query_type": "聚合查詢",
        "handling": "執行",
        "sql_structure": "SELECT AVG(img10) ... GROUP BY ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-007",
        "natural_language": "查詢庫存量最高的單筆記錄的數量。",
        "query_type": "聚合查詢",
        "handling": "執行",
        "sql_structure": "SELECT MAX(img10) ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-008",
        "natural_language": "查詢庫存量最低的單筆記錄的數量。",
        "query_type": "聚合查詢",
        "handling": "執行",
        "sql_structure": "SELECT MIN(img10) ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-009",
        "natural_language": "統計料號 10-0001 的庫存記錄筆數。",
        "query_type": "聚合查詢",
        "handling": "執行",
        "sql_structure": "SELECT COUNT(*) ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-010",
        "natural_language": "按倉庫統計總庫存量。",
        "query_type": "分組查詢",
        "handling": "執行",
        "sql_structure": "GROUP BY ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-011",
        "natural_language": "查詢庫存記錄，按庫存量由小到大排序。",
        "query_type": "排序查詢",
        "handling": "執行",
        "sql_structure": "ORDER BY ... ASC",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-012",
        "natural_language": "查詢庫存記錄，按庫存量由大到小排序。",
        "query_type": "排序查詢",
        "handling": "執行",
        "sql_structure": "ORDER BY ... DESC",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-013",
        "natural_language": "查詢前 10 筆庫存記錄。",
        "query_type": "限制查詢",
        "handling": "執行",
        "sql_structure": "LIMIT 10",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-014",
        "natural_language": "查詢庫存量大於等於 100 的記錄。",
        "query_type": "範圍查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... >= ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-015",
        "natural_language": "查詢庫存量小於等於 500 的記錄。",
        "query_type": "範圍查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... <= ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-016",
        "natural_language": "查詢庫存量在 100 到 500 之間的記錄。",
        "query_type": "範圍查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... BETWEEN ... AND ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-017",
        "natural_language": "查詢當月的交易記錄。",
        "query_type": "日期查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... EXTRACT(MONTH ...)",
        "table": "mart_work_order_wide",
    },
    {
        "id": "T2S-018",
        "natural_language": "查詢庫存表前 1000 筆記錄。",
        "query_type": "限制查詢",
        "handling": "執行",
        "sql_structure": "LIMIT 1000",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-019",
        "natural_language": "查詢庫存量≥100 的料號，按料號分組加總庫存，再按總量由高到低排序取前 5 筆。",
        "query_type": "複雜查詢",
        "handling": "執行",
        "sql_structure": "WHERE + GROUP BY + ORDER BY + LIMIT",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-020",
        "natural_language": "查詢料號 10-0001、倉庫 W01、庫存量大於 50 的記錄。",
        "query_type": "複雜查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... AND ... AND ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-021",
        "natural_language": "查詢庫存總量前 5 名的料號。",
        "query_type": "Top N 查詢",
        "handling": "執行",
        "sql_structure": "GROUP BY + ORDER BY DESC + LIMIT",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-022",
        "natural_language": "查詢庫存總量最低的 5 個料號。",
        "query_type": "Bottom N 查詢",
        "handling": "執行",
        "sql_structure": "GROUP BY + ORDER BY ASC + LIMIT",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-023",
        "natural_language": "查詢料號開頭為 10- 的物料主檔。",
        "query_type": "模糊查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... LIKE '10-%'",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-024",
        "natural_language": "查詢料號為「不存在的料號-XYZ」的庫存。",
        "query_type": "簡單查詢",
        "handling": "執行",
        "sql_structure": "WHERE img01 = '...'",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-025",
        "natural_language": "查詢有庫存記錄的不重複料號列表。",
        "query_type": "DISTINCT 查詢",
        "handling": "執行",
        "sql_structure": "SELECT DISTINCT img01 FROM mart_inventory_wide",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-026",
        "natural_language": "查詢總庫存量超過 1000 的料號。",
        "query_type": "聚合+分組查詢",
        "handling": "執行",
        "sql_structure": "GROUP BY ... HAVING SUM(...) > ...",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-027",
        "natural_language": "查詢料號 10-0001 的品名與其總庫存量。",
        "query_type": "多表查詢",
        "handling": "執行",
        "sql_structure": "JOIN + GROUP BY + SUM",
        "table": "mart_inventory_wide + mart_inventory_wide",
    },
    {
        "id": "T2S-028",
        "natural_language": "查詢 2026 年 1 月的交易記錄。",
        "query_type": "日期查詢",
        "handling": "執行",
        "sql_structure": "WHERE tlf06 >= '2026-01-01' AND tlf06 < '2026-02-01'",
        "table": "mart_work_order_wide",
    },
    {
        "id": "T2S-029",
        "natural_language": "查詢批號為空的庫存記錄。",
        "query_type": "NULL 查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... IS NULL",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-030",
        "natural_language": "查詢庫存數量在 100 到 200 之間且倉庫為 W01 或 W02 的記錄。",
        "query_type": "複雜查詢",
        "handling": "執行",
        "sql_structure": "WHERE ... BETWEEN ... AND ... IN (...)",
        "table": "mart_inventory_wide",
    },
    {
        "id": "T2S-038",
        "natural_language": "'; DROP TABLE mart_inventory_wide;--",
        "query_type": "惡意輸入",
        "handling": "回絕",
        "reason": "未被授權做資料查詢以外的變更操作",
        "table": None,
    },
    # === 採購交易相關場景 ===
    {
        "id": "PUR-001",
        "natural_language": "10-0003 上個月的採購交易",
        "query_type": "採購交易查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM mart_work_order_wide WHERE tlf01 = '...' AND tlf19 = '101' AND tlf06 LIKE '上個月'",
        "table": "mart_work_order_wide",
    },
    {
        "id": "PUR-002",
        "natural_language": "查詢所有採購進貨交易",
        "query_type": "採購交易查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM mart_work_order_wide WHERE tlf19 = '101'",
        "table": "mart_work_order_wide",
    },
    {
        "id": "PUR-003",
        "natural_language": "2024 年有多少筆採購進貨",
        "query_type": "採購交易查詢",
        "handling": "執行",
        "sql_structure": "SELECT COUNT(*) FROM mart_work_order_wide WHERE tlf19 = '101' AND tlf06 LIKE '2024%'",
        "table": "mart_work_order_wide",
    },
    {
        "id": "PUR-004",
        "natural_language": "查詢料號 10-0001 的採購記錄",
        "query_type": "採購交易查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM mart_work_order_wide WHERE tlf01 = '...' AND tlf19 = '101'",
        "table": "mart_work_order_wide",
    },
    {
        "id": "PUR-005",
        "natural_language": "查詢某供應商的採購交易",
        "query_type": "採購交易查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM mart_work_order_wide WHERE tlf19 = '101' AND tlf14 = '...'",
        "table": "mart_work_order_wide",
    },
    # === 訂單相關場景 ===
    {
        "id": "ORD-001",
        "natural_language": "查詢所有訂單",
        "query_type": "訂單查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM coptc_file",
        "table": "coptc_file",
    },
    {
        "id": "ORD-002",
        "natural_language": "查詢最近 10 筆訂單",
        "query_type": "訂單查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM coptc_file ORDER BY coptc03 DESC LIMIT 10",
        "table": "coptc_file",
    },
    {
        "id": "ORD-003",
        "natural_language": "統計每個客户的訂單數量",
        "query_type": "訂單查詢",
        "handling": "執行",
        "sql_structure": "SELECT coptc02, COUNT(*) FROM coptc_file GROUP BY coptc02",
        "table": "coptc_file",
    },
    {
        "id": "ORD-004",
        "natural_language": "查詢某客戶的訂單",
        "query_type": "訂單查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM coptc_file WHERE coptc02 = '...'",
        "table": "coptc_file",
    },
    {
        "id": "ORD-005",
        "natural_language": "查詢訂單 SO-2024010001 的明細",
        "query_type": "訂單查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM coptd_file WHERE coptd01 = '...'",
        "table": "coptd_file",
    },
    # === 採購單相關場景 ===
    {
        "id": "PO-001",
        "natural_language": "查詢所有採購單",
        "query_type": "採購單查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM pmm_file",
        "table": "pmm_file",
    },
    {
        "id": "PO-002",
        "natural_language": "按供應商統計採購單數量",
        "query_type": "採購單查詢",
        "handling": "執行",
        "sql_structure": "SELECT pmm04, COUNT(*) FROM pmm_file GROUP BY pmm04",
        "table": "pmm_file",
    },
    {
        "id": "PO-003",
        "natural_language": "查詢採購單 PO-2024010001 的明細",
        "query_type": "採購單查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM pmn_file WHERE pmn01 = '...'",
        "table": "pmn_file",
    },
    # === 收料單相關場景 ===
    {
        "id": "RCV-001",
        "natural_language": "查詢所有收料記錄",
        "query_type": "收料單查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM rvb_file",
        "table": "rvb_file",
    },
    {
        "id": "RCV-002",
        "natural_language": "查詢某採購單的收料記錄",
        "query_type": "收料單查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM rvb_file WHERE rvb07 = '...'",
        "table": "rvb_file",
    },
    # === 客戶相關場景 ===
    {
        "id": "CUS-001",
        "natural_language": "查詢所有客戶",
        "query_type": "客戶查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM cmc_file",
        "table": "cmc_file",
    },
    {
        "id": "CUS-002",
        "natural_language": "某客戶的聯絡人",
        "query_type": "客戶查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM cmc_file WHERE cmc01 = '...'",
        "table": "cmc_file",
    },
    # === 供應商相關場景 ===
    {
        "id": "VEN-001",
        "natural_language": "查詢所有供應商",
        "query_type": "供應商查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM pmc_file",
        "table": "pmc_file",
    },
    {
        "id": "VEN-002",
        "natural_language": "某供應商的聯絡人",
        "query_type": "供應商查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM pmc_file WHERE pmc01 = '...'",
        "table": "pmc_file",
    },
    # === 價格相關場景 ===
    {
        "id": "PRC-001",
        "natural_language": "查詢料號 10-0001 的單價",
        "query_type": "價格查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM prc_file WHERE prc01 = '...'",
        "table": "prc_file",
    },
    {
        "id": "PRC-002",
        "natural_language": "料號 10-0001 的最新報價",
        "query_type": "價格查詢",
        "handling": "執行",
        "sql_structure": "SELECT * FROM prc_file WHERE prc01 = '...' ORDER BY prc03 DESC LIMIT 1",
        "table": "prc_file",
    },
]

# 查詢類型定義
QUERY_TYPES = [
    "簡單查詢",
    "聚合查詢",
    "分組查詢",
    "排序查詢",
    "限制查詢",
    "範圍查詢",
    "日期查詢",
    "複雜查詢",
    "Top N 查詢",
    "Bottom N 查詢",
    "模糊查詢",
    "DISTINCT 查詢",
    "聚合+分組查詢",
    "多表查詢",
    "NULL 查詢",
    "惡意輸入",
    "語義不清楚",
    "採購交易查詢",
    "訂單查詢",
    "採購單查詢",
    "收料單查詢",
    "客戶查詢",
    "供應商查詢",
    "價格查詢",
]

# 處置方式定義
HANDLING_TYPES = [
    "執行",
    "回問",
    "回絕",
]
