# ========================================
# Workflow: inventory_counting
# ========================================

name: "inventory_counting"
description: "保持庫存數據準確"
version: "1.0.0"

triggers:
  - "盤點"
  - "盤點作業"
  - "庫存盤點"
  - "每月全盤盤點"
  - "循環盤點週期"

workflow:
  steps:
    - step_id: 1
      action_type: "data_query"
      description: "向 Data-Agent 查詢：『請提供 ERP 中所有物料最新庫存數據及 AB..."
      instruction: |
        向 Data-Agent 查詢：『請提供 ERP 中所有物料最新庫存數據及 ABC 分類，JSON 格式』
    - step_id: 2
      action_type: "data_cleaning"
      description: "資料完整性檢查：確認每個物料都有庫存數量與 ABC 分類，缺失則重新調用"
      instruction: |
        資料完整性檢查：確認每個物料都有庫存數量與 ABC 分類，缺失則重新調用
    - step_id: 3
      action_type: "computation"
      description: "生成盤點清單（全盤或循環盤點）"
      instruction: |
        生成盤點清單（全盤或循環盤點）
    - step_id: 4
      action_type: "data_query"
      description: "現場盤點實物數量"
      instruction: |
        現場盤點實物數量
    - step_id: 5
      action_type: "computation"
      description: "比對 ERP 數據，計算差異"
      instruction: |
        比對 ERP 數據，計算差異
    - step_id: 6
      action_type: "data_query"
      description: "調整 ERP 庫存紀錄"
      instruction: |
        調整 ERP 庫存紀錄
    - step_id: 7
      action_type: "computation"
      description: "生成盤點報告及差異分析"
      instruction: |
        生成盤點報告及差異分析
