# 代碼功能說明: API 路由模組初始化文件
# 創建日期: 2025-01-27
# 創建人: Daniel Chung
# 最後修改日期: 2026-01-17 18:07 UTC+8

"""API 路由模組 - 提供所有 API 端點的路由定義"""

from . import (
    agent_catalog,
    agent_display_config,
    agent_files,
    agent_registry,
    agents,
    chat,
    chromadb,
    chunk_processing,
    docs_editing,
    execution,
    file_management,
    file_metadata,
    file_upload,
    genai_tenant_config,
    genai_user_config,
    health,
    kg_builder,
    kg_query,
    llm,
    mcp,
    ner,
    orchestrator,
    planning,
    re,
    reports,
    review,
    rt,
    service_monitor,
    system_admin,
    task_analyzer,
    tools_registry,
    triple_extraction,
    user_account,
    user_sessions,
    user_tasks,
    workflows,
)

__all__ = [
    "health",
    "agents",
    "task_analyzer",
    "orchestrator",
    "planning",
    "execution",
    "review",
    "mcp",
    "chromadb",
    "llm",
    "chat",
    "docs_editing",
    "genai_tenant_config",
    "genai_user_config",
    "file_upload",
    "chunk_processing",
    "file_metadata",
    "file_management",
    "user_tasks",
    "ner",
    "re",
    "rt",
    "triple_extraction",
    "kg_builder",
    "kg_query",
    "workflows",
    "agent_registry",
    "agent_catalog",
    "agent_display_config",
    "agent_files",
    "reports",
    "tools_registry",
    "system_admin",
    "service_monitor",
    "user_account",
    "user_sessions",
]
